name: CD

on:
  push:
    branches: [ master ]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install dependencies
        name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
        run: npm install
      - name: Build
        run: npm run build

  deploy_to_dev: 
    runs-on: ubuntu-latest
    needs: build
    environment: development

    steps: 
      - uses: actions/checkout@v2
      - name: Deploy to vps
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: | 
            cd /home/dopas/weather-pwa
            git pull origin master
            npm cache clean --force
            npm install
            npm run build
            pm2 restart
