name: CD

on:
  push:
    branches: [ master ]

jobs:
  build: 
    runs-on: ubuntu-latest
    environment: master
        
    steps: 
      - uses: actions/checkout@v2
      - name: Deploy to vps
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: | 
            cd /home/dopas/weather-pwa
            git pull origin master
            npm cache clean --force
            npm install
            npm run build
            pm2 restart 
